/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApiKeyRouteImport } from './routes/api-key'
import { Route as CartRouteImport } from './routes/cart'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminApiShopsRouteImport } from './routes/admin.api-shops'
import { Route as AdminBotButtonsRouteImport } from './routes/admin.bot-buttons'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminHostingRouteImport } from './routes/admin.hosting'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminEditProductIdRouteImport } from './routes/admin.edit.$productId'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay/webhook'
import { Route as ApiPublicResellerSplatRouteImport } from './routes/api/public/reseller/$'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeyRoute = ApiKeyRouteImport.update({
  id: '/api-key',
  path: '/api-key',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApiShopsRoute = AdminApiShopsRouteImport.update({
  id: '/api-shops',
  path: '/api-shops',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBotButtonsRoute = AdminBotButtonsRouteImport.update({
  id: '/bot-buttons',
  path: '/bot-buttons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHostingRoute = AdminHostingRouteImport.update({
  id: '/hosting',
  path: '/hosting',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditProductIdRoute = AdminEditProductIdRouteImport.update({
  id: '/edit/$productId',
  path: '/edit/$productId',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay/webhook',
    path: '/api/public/razorpay/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicResellerSplatRoute = ApiPublicResellerSplatRouteImport.update({
  id: '/api/public/reseller/$',
  path: '/api/public/reseller/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-key': typeof ApiKeyRoute
  '/cart': typeof CartRoute
  '/history': typeof HistoryRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/admin/api-shops': typeof AdminApiShopsRoute
  '/admin/bot-buttons': typeof AdminBotButtonsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/hosting': typeof AdminHostingRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/edit/$productId': typeof AdminEditProductIdRoute
  '/api/public/razorpay/webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/reseller/$': typeof ApiPublicResellerSplatRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-key': typeof ApiKeyRoute
  '/cart': typeof CartRoute
  '/history': typeof HistoryRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/admin/api-shops': typeof AdminApiShopsRoute
  '/admin/bot-buttons': typeof AdminBotButtonsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/hosting': typeof AdminHostingRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/admin/edit/$productId': typeof AdminEditProductIdRoute
  '/api/public/razorpay/webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/reseller/$': typeof ApiPublicResellerSplatRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-key': typeof ApiKeyRoute
  '/cart': typeof CartRoute
  '/history': typeof HistoryRoute
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/admin/api-shops': typeof AdminApiShopsRoute
  '/admin/bot-buttons': typeof AdminBotButtonsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/hosting': typeof AdminHostingRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/edit/$productId': typeof AdminEditProductIdRoute
  '/api/public/razorpay/webhook': typeof ApiPublicRazorpayWebhookRoute
  '/api/public/reseller/$': typeof ApiPublicResellerSplatRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api-key'
    | '/cart'
    | '/history'
    | '/orders'
    | '/products'
    | '/profile'
    | '/admin/api-shops'
    | '/admin/bot-buttons'
    | '/admin/coupons'
    | '/admin/hosting'
    | '/admin/products'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
    | '/admin/edit/$productId'
    | '/api/public/razorpay/webhook'
    | '/api/public/reseller/$'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-key'
    | '/cart'
    | '/history'
    | '/orders'
    | '/products'
    | '/profile'
    | '/admin/api-shops'
    | '/admin/bot-buttons'
    | '/admin/coupons'
    | '/admin/hosting'
    | '/admin/products'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/users'
    | '/admin'
    | '/admin/edit/$productId'
    | '/api/public/razorpay/webhook'
    | '/api/public/reseller/$'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api-key'
    | '/cart'
    | '/history'
    | '/orders'
    | '/products'
    | '/profile'
    | '/admin/api-shops'
    | '/admin/bot-buttons'
    | '/admin/coupons'
    | '/admin/hosting'
    | '/admin/products'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
    | '/admin/edit/$productId'
    | '/api/public/razorpay/webhook'
    | '/api/public/reseller/$'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiKeyRoute: typeof ApiKeyRoute
  CartRoute: typeof CartRoute
  HistoryRoute: typeof HistoryRoute
  OrdersRoute: typeof OrdersRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  ApiPublicResellerSplatRoute: typeof ApiPublicResellerSplatRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-key': {
      id: '/api-key'
      path: '/api-key'
      fullPath: '/api-key'
      preLoaderRoute: typeof ApiKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/api-shops': {
      id: '/admin/api-shops'
      path: '/api-shops'
      fullPath: '/admin/api-shops'
      preLoaderRoute: typeof AdminApiShopsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bot-buttons': {
      id: '/admin/bot-buttons'
      path: '/bot-buttons'
      fullPath: '/admin/bot-buttons'
      preLoaderRoute: typeof AdminBotButtonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hosting': {
      id: '/admin/hosting'
      path: '/hosting'
      fullPath: '/admin/hosting'
      preLoaderRoute: typeof AdminHostingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/edit/$productId': {
      id: '/admin/edit/$productId'
      path: '/edit/$productId'
      fullPath: '/admin/edit/$productId'
      preLoaderRoute: typeof AdminEditProductIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/razorpay/webhook': {
      id: '/api/public/razorpay/webhook'
      path: '/api/public/razorpay/webhook'
      fullPath: '/api/public/razorpay/webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reseller/$': {
      id: '/api/public/reseller/$'
      path: '/api/public/reseller/$'
      fullPath: '/api/public/reseller/$'
      preLoaderRoute: typeof ApiPublicResellerSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminApiShopsRoute: typeof AdminApiShopsRoute
  AdminBotButtonsRoute: typeof AdminBotButtonsRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminHostingRoute: typeof AdminHostingRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEditProductIdRoute: typeof AdminEditProductIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApiShopsRoute: AdminApiShopsRoute,
  AdminBotButtonsRoute: AdminBotButtonsRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminHostingRoute: AdminHostingRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEditProductIdRoute: AdminEditProductIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiKeyRoute: ApiKeyRoute,
  CartRoute: CartRoute,
  HistoryRoute: HistoryRoute,
  OrdersRoute: OrdersRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  ApiPublicResellerSplatRoute: ApiPublicResellerSplatRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
